version: '3'

volumes:
  stratbot_ci_postgres_data: {}
  stratbot_ci_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: stratbot_ci_django
    container_name: stratbot_ci_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.dev/.django.env
      - ./.envs/.dev/.postgres.env
      - ./.envs/.dev/.redis.env
      - ./.envs/.dev/.celery.env
      - ./.envs/.dev/.docker.env
      - ./.envs/.ci/.committed-to-vc-be-careful.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: stratbot_prod_postgres
    container_name: stratbot_ci_postgres
    volumes:
      - stratbot_ci_postgres_data:/var/lib/postgresql/data:Z
      - stratbot_ci_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: stratbot_ci_redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: stratbot_ci_celeryworker
    container_name: stratbot_ci_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: stratbot_ci_celerybeat
    container_name: stratbot_ci_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  node:
    build:
      context: .
      dockerfile: ./compose/dev/node/Dockerfile
    image: stratbot_ci_node
    container_name: stratbot_ci_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    env_file:
      - ./.envs/.dev/.node.env
      - ./.envs/.dev/.docker.env
      - ./.envs/.dev/.django.env
      - ./.envs/.ci/.committed-to-vc-be-careful.env
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
